config/routes.rb
Rails.application.routes.draw do
  get 'static_notes/home'
  get 'static_notes/about'
  root 'static_notes#home'

  get '/about', to: 'static_notes#about'

  resources :notes 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all 
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new 
  end

  def create 
    @note = Note.new(notes_params)

    if @note.save
      redirect_to notes_path 
    else 
      render :new 
    end 
  end 

  def edit 
    @note = Note.find(params[:id])
  end 
  
  def update
    @note = Note.find(params[:id])
  
    if @note.update(notes_params)
      redirect_to notes_path
    else
      render :edit
    end
  end

  def destroy 
    Note.find(params[:id]).destroy 
    redirect_to notes_path
  end 

  private 

  def notes_params
    params.require(:note).permit(:title, :author, :body)
  end

end 

app/controllers/static_notes_controller.rb
class StaticNotesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/static_notes_helper.rb
module StaticNotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag "navbar.css" %>

<ul>
<li><a><%= link_to 'Home', root_path %></a></li><li><a><%= link_to 'About', about_path %><a></li><li><a><%= link_to 'Post-its', notes_path %><a></li>
</ul> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostItNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %> 
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h1>-------------------- Edit Post-it -------------------- </h1>
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <textarea rows="7" cols="30"></textarea>

  <%= f.submit %>
<% end %>

<h3>Edit Title</h3>
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %> 

app/views/notes/index.html.erb
<h1>----- Post-its ----- </h1>
<p><%= link_to 'New Post-it' , new_note_path %></p> 

<% @notes.each do |note| %>
  <h3><%= note.title %></h3> 
  <%= image_tag('postit2.png') %>
  <br></br>
 
  <%= link_to 'View', note_path(note) %> 

  <%= link_to 'Edit', edit_note_path(note) %> 

  <%= link_to 'Delete', note, method: :delete %>
<% end %> 

app/views/notes/new.html.erb
<h1>New Post-it</h1>
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<br></br>
<h2> Title: <%= @note.title %></h2> 
<%= image_tag('postit2.png') %>
<br></br>
<h3> Author: <%= @note.author %></h3>
<h3> Post-it:</h3> 
<textarea rows="10" cols="50"> <%= @note.body %></textarea>
<br></br>

<%= link_to 'Back', notes_path %>

app/views/static_notes/about.html.erb
<h1>---------------- About ----------------</h1>
<p>This is an app for creating Post-it notes, reminders, or lists</p>
<%= image_tag('postitnotes.jpg') %>

app/views/static_notes/home.html.erb
<h1>------------- Post-it Note -------------</h1>


<%= image_tag('postitnotes.jpg') %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>